-- LINE OSS CRM D1 Schema
-- IDs are TEXT and generated by app code using crypto.randomUUID()

-- ============================================================
-- Friends
-- ============================================================
CREATE TABLE IF NOT EXISTS friends (
  id                  TEXT PRIMARY KEY,
  line_user_id        TEXT UNIQUE NOT NULL,
  display_name        TEXT,
  picture_url         TEXT,
  status_message      TEXT,
  is_following        INTEGER NOT NULL DEFAULT 1,
  user_id             TEXT,
  ig_igsid            TEXT,
  score               INTEGER NOT NULL DEFAULT 0,
  ai_chat_paused      INTEGER NOT NULL DEFAULT 0,
  ai_chat_paused_at   TEXT,
  lstep_friend_id     TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friends_line_user_id ON friends (line_user_id);
CREATE INDEX IF NOT EXISTS idx_friends_user_id ON friends (user_id);
CREATE INDEX IF NOT EXISTS idx_friends_ig_igsid ON friends (ig_igsid);
CREATE INDEX IF NOT EXISTS idx_friends_ai_chat_paused ON friends (ai_chat_paused);
CREATE INDEX IF NOT EXISTS idx_friends_lstep_friend_id ON friends (lstep_friend_id);
CREATE INDEX IF NOT EXISTS idx_friends_line_account_id ON friends (line_account_id);

-- ============================================================
-- Tags
-- ============================================================
CREATE TABLE IF NOT EXISTS tags (
  id         TEXT PRIMARY KEY,
  name       TEXT UNIQUE NOT NULL,
  color      TEXT NOT NULL DEFAULT '#3B82F6',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Friend <-> Tag join
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_tags (
  friend_id   TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  tag_id      TEXT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  PRIMARY KEY (friend_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_friend_tags_tag_id ON friend_tags (tag_id);

-- ============================================================
-- Scenarios
-- ============================================================
CREATE TABLE IF NOT EXISTS scenarios (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  description     TEXT,
  trigger_type    TEXT NOT NULL CHECK (trigger_type IN ('friend_add', 'tag_added', 'manual')),
  trigger_tag_id  TEXT REFERENCES tags (id) ON DELETE SET NULL,
  is_active       INTEGER NOT NULL DEFAULT 1,
  delivery_mode   TEXT NOT NULL DEFAULT 'relative' CHECK (delivery_mode IN ('relative', 'elapsed', 'absolute_time')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Scenario Steps
-- ============================================================
CREATE TABLE IF NOT EXISTS scenario_steps (
  id              TEXT PRIMARY KEY,
  scenario_id     TEXT NOT NULL REFERENCES scenarios (id) ON DELETE CASCADE,
  step_order      INTEGER NOT NULL,
  delay_minutes   INTEGER NOT NULL DEFAULT 0,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  offset_days     INTEGER,
  offset_minutes  INTEGER,
  delivery_time   TEXT,
  template_id     TEXT REFERENCES templates(id) ON DELETE SET NULL,
  on_reach_tag_id TEXT REFERENCES tags(id) ON DELETE SET NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (scenario_id, step_order)
);

CREATE INDEX IF NOT EXISTS idx_scenario_steps_scenario_id ON scenario_steps (scenario_id);
CREATE INDEX IF NOT EXISTS idx_scenarios_line_account_id ON scenarios (line_account_id);

-- ============================================================
-- Friend Scenario Enrollments
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_scenarios (
  id                 TEXT PRIMARY KEY,
  friend_id          TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  scenario_id        TEXT NOT NULL REFERENCES scenarios (id) ON DELETE CASCADE,
  current_step_order INTEGER NOT NULL DEFAULT 0,
  status             TEXT NOT NULL CHECK (status IN ('active', 'paused', 'completed', 'delivering')) DEFAULT 'active',
  started_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  next_delivery_at   TEXT,
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_scenarios_next_delivery_at ON friend_scenarios (next_delivery_at);
CREATE INDEX IF NOT EXISTS idx_friend_scenarios_status ON friend_scenarios (status);
CREATE INDEX IF NOT EXISTS idx_friend_scenarios_friend_id ON friend_scenarios (friend_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_friend_scenarios_unique ON friend_scenarios (friend_id, scenario_id) WHERE status != 'completed';

-- ============================================================
-- Broadcasts
-- ============================================================
CREATE TABLE IF NOT EXISTS broadcasts (
  id              TEXT PRIMARY KEY,
  title           TEXT NOT NULL,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  target_type     TEXT NOT NULL CHECK (target_type IN ('all', 'tag', 'segment', 'multi-account-dedup')) DEFAULT 'all',
  target_tag_id   TEXT REFERENCES tags (id) ON DELETE SET NULL,
  status          TEXT NOT NULL CHECK (status IN ('draft', 'scheduled', 'sending', 'sent')) DEFAULT 'draft',
  scheduled_at    TEXT,
  sent_at         TEXT,
  total_count     INTEGER NOT NULL DEFAULT 0,
  success_count   INTEGER NOT NULL DEFAULT 0,
  line_request_id   TEXT,
  aggregation_unit  TEXT,
  batch_offset    INTEGER NOT NULL DEFAULT 0,
  segment_conditions TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  account_ids        TEXT CHECK (account_ids IS NULL OR json_valid(account_ids)),
  dedup_priority     TEXT CHECK (dedup_priority IS NULL OR json_valid(dedup_priority)),
  failed_account_ids TEXT CHECK (failed_account_ids IS NULL OR json_valid(failed_account_ids)),
  dedup_progress     TEXT CHECK (dedup_progress IS NULL OR json_valid(dedup_progress)),
  batch_lock_at      TEXT,
  target_segment_tag_id TEXT REFERENCES segment_tags (id) ON DELETE SET NULL,
  video_original_url TEXT,
  video_preview_url  TEXT,
  video_duration_ms  INTEGER
);

CREATE INDEX IF NOT EXISTS idx_broadcasts_status ON broadcasts (status);
CREATE INDEX IF NOT EXISTS idx_broadcasts_line_account_id ON broadcasts (line_account_id);

-- ============================================================
-- Segment Tags (Migration 055): アカウント別カスタムセグメント + AI 自動付与
-- ============================================================
CREATE TABLE IF NOT EXISTS segment_tags (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  criteria        TEXT NOT NULL,
  color           TEXT NOT NULL DEFAULT '#3B82F6',
  is_ai_managed   INTEGER NOT NULL DEFAULT 1,
  last_run_at     TEXT,
  assigned_count  INTEGER NOT NULL DEFAULT 0,
  lstep_tag_id    TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE(line_account_id, name)
);

CREATE INDEX IF NOT EXISTS idx_segment_tags_account ON segment_tags (line_account_id);
CREATE INDEX IF NOT EXISTS idx_segment_tags_lstep ON segment_tags (lstep_tag_id);

-- ============================================================
-- Card Messages (Migration 061): 公式 LINE 風カード型メッセージ
-- Flex Carousel JSON を生成して送信時は messageType='flex' で流す
-- ============================================================
CREATE TABLE IF NOT EXISTS card_messages (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  card_type       TEXT NOT NULL CHECK (card_type IN ('product', 'location', 'person', 'image')),
  cards_json      TEXT NOT NULL,
  flex_json       TEXT,
  alt_text        TEXT,
  more_card_json  TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);
CREATE INDEX IF NOT EXISTS idx_card_messages_account ON card_messages (line_account_id, updated_at DESC);

-- ============================================================
-- Coupons (Migration 062): クーポン管理 (公式 LINE 相当)
-- ============================================================
CREATE TABLE IF NOT EXISTS coupons (
  id                       TEXT PRIMARY KEY,
  line_account_id          TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  name                     TEXT NOT NULL,
  acquisition_condition    TEXT NOT NULL DEFAULT 'none',
  valid_from               TEXT NOT NULL,
  valid_to                 TEXT NOT NULL,
  timezone                 TEXT NOT NULL DEFAULT 'Asia/Tokyo',
  image_url                TEXT,
  usage_guide              TEXT,
  max_uses_per_friend      INTEGER NOT NULL DEFAULT 1,
  show_code                INTEGER NOT NULL DEFAULT 0,
  code_value               TEXT,
  coupon_type              TEXT NOT NULL DEFAULT 'discount',
  discount_mode            TEXT,
  discount_yen             INTEGER,
  discount_percent         INTEGER,
  strikethrough_before     INTEGER,
  strikethrough_after      INTEGER,
  condition_text           TEXT,
  status                   TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);
CREATE INDEX IF NOT EXISTS idx_coupons_account ON coupons (line_account_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_coupons_valid ON coupons (line_account_id, valid_from, valid_to);

CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id          TEXT PRIMARY KEY,
  coupon_id   TEXT NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
  friend_id   TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  used_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  staff_id    TEXT REFERENCES staff_members(id) ON DELETE SET NULL,
  note        TEXT
);
CREATE INDEX IF NOT EXISTS idx_redemptions_coupon ON coupon_redemptions (coupon_id, used_at DESC);
CREATE INDEX IF NOT EXISTS idx_redemptions_friend ON coupon_redemptions (friend_id, coupon_id);

CREATE TABLE IF NOT EXISTS friend_segment_tags (
  friend_id        TEXT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  segment_tag_id   TEXT NOT NULL REFERENCES segment_tags(id) ON DELETE CASCADE,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  assigned_by      TEXT NOT NULL DEFAULT 'ai' CHECK (assigned_by IN ('ai','manual')),
  confidence       INTEGER,
  reason           TEXT,
  assigned_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  PRIMARY KEY (friend_id, segment_tag_id)
);

CREATE INDEX IF NOT EXISTS idx_fst_segment ON friend_segment_tags (segment_tag_id);
CREATE INDEX IF NOT EXISTS idx_fst_account_friend ON friend_segment_tags (line_account_id, friend_id);

-- ============================================================
--- Account Settings
--- ============================================================
CREATE TABLE IF NOT EXISTS account_settings (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL,
  key             TEXT NOT NULL,
  value           TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE(line_account_id, key)
);

-- ============================================================
-- Broadcast Insights
-- ============================================================
CREATE TABLE IF NOT EXISTS broadcast_insights (
  id                  TEXT PRIMARY KEY,
  broadcast_id        TEXT NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  delivered           INTEGER,
  unique_impression   INTEGER,
  unique_click        INTEGER,
  unique_media_played INTEGER,
  open_rate           REAL,
  click_rate          REAL,
  raw_response        TEXT,
  status              TEXT NOT NULL CHECK (status IN ('pending', 'ready', 'failed')),
  retry_count         INTEGER NOT NULL DEFAULT 0,
  fetched_at          TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_broadcast_insights_broadcast_id ON broadcast_insights(broadcast_id);
CREATE INDEX IF NOT EXISTS idx_broadcast_insights_status ON broadcast_insights(status);

-- ============================================================
-- Messages Log
-- ============================================================
CREATE TABLE IF NOT EXISTS messages_log (
  id               TEXT PRIMARY KEY,
  friend_id        TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  direction        TEXT NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
  message_type     TEXT NOT NULL,
  content          TEXT NOT NULL,
  broadcast_id     TEXT REFERENCES broadcasts (id) ON DELETE SET NULL,
  scenario_step_id TEXT REFERENCES scenario_steps (id) ON DELETE SET NULL,
  template_id_at_send TEXT,
  delivery_type    TEXT CHECK (delivery_type IN ('push', 'reply', 'test')),
  source           TEXT,
  line_account_id  TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_messages_log_broadcast_id ON messages_log(broadcast_id);

CREATE INDEX IF NOT EXISTS idx_messages_log_friend_id ON messages_log (friend_id);
CREATE INDEX IF NOT EXISTS idx_messages_log_created_at ON messages_log (created_at);
CREATE INDEX IF NOT EXISTS idx_messages_log_friend_source ON messages_log (friend_id, source);
CREATE INDEX IF NOT EXISTS idx_messages_log_friend_direction_created ON messages_log (friend_id, direction, created_at);

-- ============================================================
-- Auto Replies
-- ============================================================
CREATE TABLE IF NOT EXISTS auto_replies (
  id               TEXT PRIMARY KEY,
  keyword          TEXT NOT NULL,
  match_type       TEXT NOT NULL CHECK (match_type IN ('exact', 'contains')) DEFAULT 'exact',
  response_type    TEXT NOT NULL DEFAULT 'text',
  response_content TEXT NOT NULL,
  template_id      TEXT REFERENCES templates(id) ON DELETE SET NULL,
  line_account_id  TEXT DEFAULT NULL,
  is_active        INTEGER NOT NULL DEFAULT 1,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_auto_replies_template_id ON auto_replies(template_id);

-- ============================================================
-- Admin Users
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Internal UUID Users (Cross-Account)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id           TEXT PRIMARY KEY,
  email        TEXT,
  phone        TEXT,
  external_id  TEXT,
  display_name TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_external_id ON users (external_id);

-- ============================================================
-- Round 2: LINE Account Management (Multi-Account)
-- ============================================================
CREATE TABLE IF NOT EXISTS line_accounts (
  id                   TEXT PRIMARY KEY,
  channel_id           TEXT NOT NULL UNIQUE,
  name                 TEXT NOT NULL,
  channel_access_token TEXT NOT NULL,
  channel_secret       TEXT NOT NULL,
  is_active            INTEGER NOT NULL DEFAULT 1,
  country              TEXT,
  role                 TEXT,
  display_order        INTEGER NOT NULL DEFAULT 0,
  display_name         TEXT,
  picture_url          TEXT,
  basic_id             TEXT,
  profile_refreshed_at TEXT,
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_line_accounts_display_order
  ON line_accounts (display_order, created_at);

-- ============================================================
-- Round 2: Conversion Points (CV Tracking)
-- ============================================================
CREATE TABLE IF NOT EXISTS conversion_points (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  event_type      TEXT NOT NULL,
  value           REAL,
  line_account_id TEXT REFERENCES line_accounts (id) ON DELETE CASCADE,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);
CREATE INDEX IF NOT EXISTS idx_conversion_points_account ON conversion_points (line_account_id);

-- ============================================================
-- Round 2: Conversion Events (CV Records)
-- ============================================================
CREATE TABLE IF NOT EXISTS conversion_events (
  id                  TEXT PRIMARY KEY,
  conversion_point_id TEXT NOT NULL REFERENCES conversion_points (id) ON DELETE CASCADE,
  friend_id           TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  user_id             TEXT,
  affiliate_code      TEXT,
  metadata            TEXT,
  line_account_id     TEXT REFERENCES line_accounts (id) ON DELETE CASCADE,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_conversion_events_point ON conversion_events (conversion_point_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_friend ON conversion_events (friend_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_affiliate ON conversion_events (affiliate_code);
CREATE INDEX IF NOT EXISTS idx_conversion_events_account ON conversion_events (line_account_id);

-- ============================================================
-- Round 2: Affiliates
-- ============================================================
CREATE TABLE IF NOT EXISTS affiliates (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  code            TEXT NOT NULL UNIQUE,
  commission_rate REAL NOT NULL DEFAULT 0,
  is_active       INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Affiliate Clicks
-- ============================================================
CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id           TEXT PRIMARY KEY,
  affiliate_id TEXT NOT NULL REFERENCES affiliates (id) ON DELETE CASCADE,
  url          TEXT,
  ip_address   TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate ON affiliate_clicks (affiliate_id);

-- ============================================================
-- Round 3: Webhook IN/OUT
-- ============================================================
CREATE TABLE IF NOT EXISTS incoming_webhooks (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'custom',
  secret      TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS outgoing_webhooks (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  url         TEXT NOT NULL,
  event_types TEXT NOT NULL DEFAULT '[]',
  secret      TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 3: Google Calendar
-- ============================================================
CREATE TABLE IF NOT EXISTS google_calendar_connections (
  id            TEXT PRIMARY KEY,
  calendar_id   TEXT NOT NULL,
  access_token  TEXT,
  refresh_token TEXT,
  api_key       TEXT,
  auth_type     TEXT NOT NULL DEFAULT 'api_key',
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS calendar_bookings (
  id             TEXT PRIMARY KEY,
  connection_id  TEXT NOT NULL REFERENCES google_calendar_connections (id) ON DELETE CASCADE,
  friend_id      TEXT REFERENCES friends (id) ON DELETE SET NULL,
  event_id       TEXT,
  title          TEXT NOT NULL,
  start_at       TEXT NOT NULL,
  end_at         TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
  metadata       TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_calendar_bookings_friend ON calendar_bookings (friend_id);
CREATE INDEX IF NOT EXISTS idx_calendar_bookings_start ON calendar_bookings (start_at);

-- ============================================================
-- Round 3: リマインダ配信
-- ============================================================
CREATE TABLE IF NOT EXISTS reminders (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reminder_steps (
  id              TEXT PRIMARY KEY,
  reminder_id     TEXT NOT NULL REFERENCES reminders (id) ON DELETE CASCADE,
  offset_minutes  INTEGER NOT NULL,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_reminder_steps_reminder ON reminder_steps (reminder_id);

CREATE TABLE IF NOT EXISTS friend_reminders (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  reminder_id     TEXT NOT NULL REFERENCES reminders (id) ON DELETE CASCADE,
  target_date     TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_reminders_status ON friend_reminders (status);
CREATE INDEX IF NOT EXISTS idx_friend_reminders_friend ON friend_reminders (friend_id);
CREATE INDEX IF NOT EXISTS idx_reminders_line_account_id ON reminders (line_account_id);

CREATE TABLE IF NOT EXISTS friend_reminder_deliveries (
  id                TEXT PRIMARY KEY,
  friend_reminder_id TEXT NOT NULL REFERENCES friend_reminders (id) ON DELETE CASCADE,
  reminder_step_id  TEXT NOT NULL REFERENCES reminder_steps (id) ON DELETE CASCADE,
  delivered_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (friend_reminder_id, reminder_step_id)
);

-- ============================================================
-- Round 3: スコアリング
-- ============================================================
CREATE TABLE IF NOT EXISTS scoring_rules (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  event_type  TEXT NOT NULL,
  score_value INTEGER NOT NULL,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS friend_scores (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  scoring_rule_id TEXT REFERENCES scoring_rules (id) ON DELETE SET NULL,
  score_change    INTEGER NOT NULL,
  reason          TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_scores_friend ON friend_scores (friend_id);
CREATE INDEX IF NOT EXISTS idx_friend_scores_created ON friend_scores (created_at);

-- ============================================================
-- Round 3: テンプレート管理
-- ============================================================
CREATE TABLE IF NOT EXISTS templates (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  category        TEXT NOT NULL DEFAULT 'general',
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex', 'carousel')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_templates_category ON templates (category);

-- ============================================================
-- Round 3: オペレーター/チャット
-- ============================================================
CREATE TABLE IF NOT EXISTS operators (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL UNIQUE,
  role       TEXT NOT NULL DEFAULT 'operator' CHECK (role IN ('admin', 'operator')),
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS chats (
  id            TEXT PRIMARY KEY,
  friend_id     TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  operator_id   TEXT REFERENCES operators (id) ON DELETE SET NULL,
  status        TEXT NOT NULL DEFAULT 'unread' CHECK (status IN ('unread', 'in_progress', 'resolved')),
  notes         TEXT,
  last_message_at TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_chats_friend ON chats (friend_id);
CREATE INDEX IF NOT EXISTS idx_chats_operator ON chats (operator_id);
CREATE INDEX IF NOT EXISTS idx_chats_status ON chats (status);
CREATE INDEX IF NOT EXISTS idx_chats_line_account_id ON chats (line_account_id);

-- ============================================================
-- Round 3: 通知機能
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_rules (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  event_type   TEXT NOT NULL,
  conditions   TEXT NOT NULL DEFAULT '{}',
  channels     TEXT NOT NULL DEFAULT '["webhook"]',
  is_active    INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS notifications (
  id              TEXT PRIMARY KEY,
  rule_id         TEXT REFERENCES notification_rules (id) ON DELETE SET NULL,
  event_type      TEXT NOT NULL,
  title           TEXT NOT NULL,
  body            TEXT NOT NULL,
  channel         TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  metadata        TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications (status);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications (created_at);

-- ============================================================
-- Round 3: Stripe決済連携
-- ============================================================
CREATE TABLE IF NOT EXISTS stripe_events (
  id               TEXT PRIMARY KEY,
  stripe_event_id  TEXT NOT NULL UNIQUE,
  event_type       TEXT NOT NULL,
  friend_id        TEXT REFERENCES friends (id) ON DELETE SET NULL,
  amount           REAL,
  currency         TEXT,
  metadata         TEXT,
  processed_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_friend ON stripe_events (friend_id);
CREATE INDEX IF NOT EXISTS idx_stripe_events_type ON stripe_events (event_type);

-- ============================================================
-- Round 3: BAN検知 & リカバリ
-- ============================================================
CREATE TABLE IF NOT EXISTS account_health_logs (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL,
  error_code      INTEGER,
  error_count     INTEGER NOT NULL DEFAULT 0,
  check_period    TEXT NOT NULL,
  risk_level      TEXT NOT NULL DEFAULT 'normal' CHECK (risk_level IN ('normal', 'warning', 'danger')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_health_logs_account ON account_health_logs (line_account_id);

CREATE TABLE IF NOT EXISTS account_migrations (
  id               TEXT PRIMARY KEY,
  from_account_id  TEXT NOT NULL,
  to_account_id    TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'failed')),
  migrated_count   INTEGER NOT NULL DEFAULT 0,
  total_count      INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  completed_at     TEXT
);

-- ============================================================
-- Round 3: アクション自動化
-- ============================================================
CREATE TABLE IF NOT EXISTS automations (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  event_type  TEXT NOT NULL,
  conditions  TEXT NOT NULL DEFAULT '{}',
  actions     TEXT NOT NULL DEFAULT '[]',
  is_active   INTEGER NOT NULL DEFAULT 1,
  priority    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_automations_event ON automations (event_type);
CREATE INDEX IF NOT EXISTS idx_automations_active ON automations (is_active);
CREATE INDEX IF NOT EXISTS idx_automations_line_account_id ON automations (line_account_id);

CREATE TABLE IF NOT EXISTS automation_logs (
  id             TEXT PRIMARY KEY,
  automation_id  TEXT NOT NULL REFERENCES automations (id) ON DELETE CASCADE,
  friend_id      TEXT REFERENCES friends (id) ON DELETE SET NULL,
  event_data     TEXT,
  actions_result TEXT,
  status         TEXT NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'partial', 'failed')),
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_automation_logs_automation ON automation_logs (automation_id);

-- ============================================================
-- Ad Platform Configuration
-- ============================================================
CREATE TABLE IF NOT EXISTS ad_platforms (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  display_name TEXT,
  config       TEXT NOT NULL DEFAULT '{}',
  is_active    INTEGER DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Ad Conversion Logs
-- ============================================================
CREATE TABLE IF NOT EXISTS ad_conversion_logs (
  id                  TEXT PRIMARY KEY,
  ad_platform_id      TEXT NOT NULL,
  friend_id           TEXT NOT NULL,
  conversion_point_id TEXT,
  event_name          TEXT NOT NULL,
  click_id            TEXT,
  click_id_type       TEXT,
  status              TEXT DEFAULT 'pending',
  request_body        TEXT,
  response_body       TEXT,
  error_message       TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_platform ON ad_conversion_logs (ad_platform_id);
CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_friend ON ad_conversion_logs (friend_id);
CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_status ON ad_conversion_logs (status);

-- Staff member accounts with role-based access control
CREATE TABLE IF NOT EXISTS staff_members (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT,
  role          TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'staff')),
  api_key       TEXT UNIQUE NOT NULL,
  api_key_hash  TEXT,
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_members_api_key ON staff_members(api_key);
CREATE INDEX IF NOT EXISTS idx_staff_members_api_key_hash ON staff_members (api_key_hash);
CREATE INDEX IF NOT EXISTS idx_staff_members_role ON staff_members(role);

-- Reusable message templates (text or Flex) for reward messages in campaigns
CREATE TABLE IF NOT EXISTS message_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  message_type TEXT NOT NULL CHECK (message_type IN ('text', 'flex')),
  message_content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Pool accounts — multiple LINE accounts per traffic pool for distribution
CREATE TABLE IF NOT EXISTS pool_accounts (
  id TEXT PRIMARY KEY,
  pool_id TEXT NOT NULL REFERENCES traffic_pools(id) ON DELETE CASCADE,
  line_account_id TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(pool_id, line_account_id)
);
-- Migration 036: Booking feature (Phase 1)
-- See: docs/superpowers/specs/2026-05-08-booking-design.md
--
-- Conventions follow schema.sql: TEXT (UUID/nanoid) primary keys,
-- created_at default in JST. Time-of-event columns (starts_at / ends_at /
-- block_ends_at / requested_at / scheduled_at / sent_at / decided_at /
-- expires_at) are written by the Worker as UTC ISO8601 (Z-suffixed) and
-- have NO default — callers must provide them.

-- ============================================================
-- menus: メニューマスタ
-- ============================================================
CREATE TABLE IF NOT EXISTS menus (
  id                    TEXT PRIMARY KEY,
  line_account_id       TEXT NOT NULL,
  name                  TEXT NOT NULL,
  category_label        TEXT,
  description           TEXT,
  duration_minutes      INTEGER NOT NULL,
  buffer_after_minutes  INTEGER NOT NULL DEFAULT 0,
  base_price            INTEGER NOT NULL,
  sort_order            INTEGER NOT NULL DEFAULT 0,
  is_active             INTEGER NOT NULL DEFAULT 1,
  deleted_at            TEXT,
  created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  FOREIGN KEY (line_account_id) REFERENCES line_accounts(id)
);
CREATE INDEX IF NOT EXISTS idx_menus_account_sort ON menus (line_account_id, sort_order);

-- ============================================================
-- staff: スタッフ
-- ============================================================
CREATE TABLE IF NOT EXISTS staff (
  id                       TEXT PRIMARY KEY,
  line_account_id          TEXT NOT NULL,
  name                     TEXT NOT NULL,
  display_name             TEXT NOT NULL,
  role                     TEXT,
  profile_image_url        TEXT,
  bio                      TEXT,
  sort_order               INTEGER NOT NULL DEFAULT 0,
  is_designation_optional  INTEGER NOT NULL DEFAULT 0,
  is_active                INTEGER NOT NULL DEFAULT 1,
  deleted_at               TEXT,
  created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  FOREIGN KEY (line_account_id) REFERENCES line_accounts(id)
);
CREATE INDEX IF NOT EXISTS idx_staff_account_sort ON staff (line_account_id, sort_order);

-- ============================================================
-- staff_menus: スタッフ x メニュー (提供可否・上書き値)
-- ============================================================
CREATE TABLE IF NOT EXISTS staff_menus (
  staff_id                  TEXT NOT NULL,
  menu_id                   TEXT NOT NULL,
  is_offered                INTEGER NOT NULL DEFAULT 1,
  override_duration_minutes INTEGER,
  override_price            INTEGER,
  PRIMARY KEY (staff_id, menu_id),
  FOREIGN KEY (staff_id) REFERENCES staff(id),
  FOREIGN KEY (menu_id) REFERENCES menus(id)
);

-- ============================================================
-- staff_shifts: シフト (レコードなし = その日休み)
-- ============================================================
CREATE TABLE IF NOT EXISTS staff_shifts (
  id          TEXT PRIMARY KEY,
  staff_id    TEXT NOT NULL,
  work_date   TEXT NOT NULL,    -- YYYY-MM-DD (JST)
  start_time  TEXT NOT NULL,    -- HH:MM (JST)
  end_time    TEXT NOT NULL,    -- HH:MM (JST)
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (staff_id, work_date),
  FOREIGN KEY (staff_id) REFERENCES staff(id)
);
CREATE INDEX IF NOT EXISTS idx_shifts_staff_date ON staff_shifts (staff_id, work_date);

-- ============================================================
-- bookings: 予約本体
-- ============================================================
CREATE TABLE IF NOT EXISTS bookings (
  id                      TEXT PRIMARY KEY,
  line_account_id         TEXT NOT NULL,
  friend_id               TEXT NOT NULL,        -- friends.id
  staff_id                TEXT NOT NULL,
  menu_id                 TEXT NOT NULL,
  starts_at               TEXT NOT NULL,        -- UTC ISO8601 (Z)
  ends_at                 TEXT NOT NULL,        -- UTC ISO8601 (Z)
  block_ends_at           TEXT NOT NULL,        -- ends_at + buffer_after。衝突判定
  status                  TEXT NOT NULL CHECK (status IN ('requested','confirmed','rejected','expired','cancelled','completed','no_show')),
  customer_note           TEXT,
  internal_note           TEXT,
  price_at_booking        INTEGER NOT NULL,
  requested_at            TEXT NOT NULL,        -- UTC ISO8601
  decided_at              TEXT,                 -- UTC ISO8601
  decided_by_staff_id     TEXT,
  external_event_id       TEXT,                 -- Phase 3 余地 (Google Calendar)
  external_calendar_id    TEXT,                 -- Phase 3 余地
  created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  FOREIGN KEY (line_account_id) REFERENCES line_accounts(id),
  FOREIGN KEY (friend_id) REFERENCES friends(id),
  FOREIGN KEY (staff_id) REFERENCES staff(id),
  FOREIGN KEY (menu_id) REFERENCES menus(id)
);
CREATE INDEX IF NOT EXISTS idx_bookings_account_status_starts ON bookings (line_account_id, status, starts_at);
CREATE INDEX IF NOT EXISTS idx_bookings_staff_overlap ON bookings (staff_id, status, starts_at, block_ends_at);
CREATE INDEX IF NOT EXISTS idx_bookings_friend_starts ON bookings (friend_id, starts_at DESC);

-- ============================================================
-- booking_idempotency_keys: LIFF 多重送信防止
-- ============================================================
CREATE TABLE IF NOT EXISTS booking_idempotency_keys (
  key              TEXT PRIMARY KEY,
  line_account_id  TEXT NOT NULL,
  friend_id        TEXT NOT NULL,
  response_status  INTEGER NOT NULL,
  response_body    TEXT NOT NULL,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  expires_at       TEXT NOT NULL                  -- UTC ISO8601
);
CREATE INDEX IF NOT EXISTS idx_idempotency_expires ON booking_idempotency_keys (expires_at);

-- ============================================================
-- booking_reminders: 前日 / 当日 N 時間前リマインダ
-- ============================================================
CREATE TABLE IF NOT EXISTS booking_reminders (
  id            TEXT PRIMARY KEY,
  booking_id    TEXT NOT NULL,
  kind          TEXT NOT NULL CHECK (kind IN ('day_before','hours_before')),
  scheduled_at  TEXT NOT NULL,                                -- UTC ISO8601
  sent_at       TEXT,                                         -- UTC ISO8601
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed','failed_permanent','cancelled')),
  retry_count   INTEGER NOT NULL DEFAULT 0,
  last_error    TEXT,
  FOREIGN KEY (booking_id) REFERENCES bookings(id)
);
CREATE INDEX IF NOT EXISTS idx_reminders_status_scheduled ON booking_reminders (status, scheduled_at);


-- =============================================================================
-- Rich Menu Editor (migration 035) — groups / pages / areas
-- =============================================================================
CREATE TABLE IF NOT EXISTS rich_menu_groups (
  id                 TEXT PRIMARY KEY,
  account_id         TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  name               TEXT NOT NULL,
  chat_bar_text      TEXT NOT NULL,
  size               TEXT NOT NULL CHECK (size IN ('large','compact')),
  default_page_id    TEXT,
  is_default_for_all INTEGER NOT NULL DEFAULT 0,
  status             TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  publishing_at      TEXT,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS rich_menu_pages (
  id                 TEXT PRIMARY KEY,
  group_id           TEXT NOT NULL REFERENCES rich_menu_groups(id) ON DELETE CASCADE,
  order_index        INTEGER NOT NULL,
  name               TEXT NOT NULL,
  alias_id           TEXT NOT NULL,
  line_richmenu_id   TEXT,
  image_r2_key       TEXT,
  image_content_type TEXT,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (group_id, order_index)
);

CREATE TABLE IF NOT EXISTS rich_menu_areas (
  id              TEXT PRIMARY KEY,
  page_id         TEXT NOT NULL REFERENCES rich_menu_pages(id) ON DELETE CASCADE,
  bounds_x        INTEGER NOT NULL,
  bounds_y        INTEGER NOT NULL,
  bounds_width    INTEGER NOT NULL,
  bounds_height   INTEGER NOT NULL,
  action_type     TEXT NOT NULL CHECK (action_type IN ('uri','message','postback','richmenuswitch')),
  action_data     TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_rich_menu_pages_group    ON rich_menu_pages(group_id, order_index);
CREATE INDEX IF NOT EXISTS idx_rich_menu_areas_page     ON rich_menu_areas(page_id);
CREATE INDEX IF NOT EXISTS idx_rich_menu_groups_account ON rich_menu_groups(account_id, status);
-- ============================================================================
-- 041_l_assist_ai_foundation.sql
--
-- L-アシスト AI 機能基盤
--
-- 設計方針:
--  - 既存テーブルへの ALTER は行わない（既存運用に影響を与えない）
--  - 全テーブルは line_account_id で完全テナント分離（既存マルチアカウント基盤に準拠）
--  - id は TEXT (UUID), 日時は TEXT ISO 8601 JST (既存規約に合わせる)
--  - インデックス命名は idx_<table>_<columns> 規約
--  - 既存の friends / chats / staff_members / line_accounts を尊重
--
-- 含むもの:
--  1. ナレッジベース（kb_documents, kb_chunks）
--  2. AI 商品マスタ（ai_products）
--  3. プロンプトモジュール（prompt_modules, prompt_module_versions）
--  4. AI チャット拡張メタデータ（ai_chat_metadata）
--  5. AI 応答キャッシュ（ai_response_cache）
--  6. 顧客 AI シグナル（ai_friend_signals）
--  7. AI 使用ログ（ai_usage_log）
--  8. テナント計量（tenant_metering）
--  9. 監査ログ（audit_log）
-- 10. PII 削除リクエスト（pii_deletion_requests）
-- 11. 同意管理（consent_records）
-- ============================================================================


-- ============================================================================
-- 1. ナレッジベース（FAQ, ブランドガイド, マニュアル等）
-- ============================================================================

CREATE TABLE IF NOT EXISTS kb_documents (
  id               TEXT PRIMARY KEY,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  source_type      TEXT NOT NULL CHECK (source_type IN
                     ('faq', 'product', 'brand_guide', 'manual', 'policy', 'external_url')),
  title            TEXT NOT NULL,
  content          TEXT NOT NULL,
  source_url       TEXT,
  metadata_json    TEXT,
  active           INTEGER NOT NULL DEFAULT 1,
  vector_indexed   INTEGER NOT NULL DEFAULT 0,
  created_by       TEXT REFERENCES staff_members (id) ON DELETE SET NULL,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_kb_documents_account ON kb_documents (line_account_id, source_type, active);
CREATE INDEX IF NOT EXISTS idx_kb_documents_active ON kb_documents (line_account_id, active);


-- KB チャンク（Vectorize に投入する単位）
CREATE TABLE IF NOT EXISTS kb_chunks (
  id               TEXT PRIMARY KEY,
  document_id      TEXT NOT NULL REFERENCES kb_documents (id) ON DELETE CASCADE,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  chunk_index      INTEGER NOT NULL,
  content          TEXT NOT NULL,
  vector_id        TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_kb_chunks_document ON kb_chunks (document_id);
CREATE INDEX IF NOT EXISTS idx_kb_chunks_account ON kb_chunks (line_account_id);


-- ============================================================================
-- 2. AI 商品マスタ（EC / 物販向け）
--    既存に products テーブルがないため新規。affiliates や conversion_points
--    とは別軸の「AI が回答時に参照する商品データ」。
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_products (
  id               TEXT PRIMARY KEY,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  sku              TEXT,
  name             TEXT NOT NULL,
  description      TEXT,
  price_yen        INTEGER,
  stock            INTEGER,
  image_url        TEXT,
  category         TEXT,
  tags_json        TEXT,
  active           INTEGER NOT NULL DEFAULT 1,
  vector_indexed   INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ai_products_account ON ai_products (line_account_id, active);
CREATE INDEX IF NOT EXISTS idx_ai_products_category ON ai_products (line_account_id, category);


-- ============================================================================
-- 3. プロンプトモジュール（8 種類、バージョン履歴付き）
-- ============================================================================

CREATE TABLE IF NOT EXISTS prompt_modules (
  id                  TEXT PRIMARY KEY,
  line_account_id     TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  module_type         TEXT NOT NULL CHECK (module_type IN (
                        'personality', 'voice_tone', 'business_kb', 'faq',
                        'restrictions', 'scenario', 'escalation', 'industry_preset',
                        'internal_manual', 'product_recommend', 'hearing_sheet',
                        'chat_examples', 'other'
                      )),
  current_version_id  TEXT,
  active              INTEGER NOT NULL DEFAULT 1,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (line_account_id, module_type)
);

CREATE INDEX IF NOT EXISTS idx_prompt_modules_account ON prompt_modules (line_account_id, active);


CREATE TABLE IF NOT EXISTS prompt_module_versions (
  id          TEXT PRIMARY KEY,
  module_id   TEXT NOT NULL REFERENCES prompt_modules (id) ON DELETE CASCADE,
  version     INTEGER NOT NULL,
  content     TEXT NOT NULL,
  author_id   TEXT REFERENCES staff_members (id) ON DELETE SET NULL,
  note        TEXT,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_prompt_versions_module ON prompt_module_versions (module_id, version DESC);


-- ============================================================================
-- 4. AI チャット拡張メタデータ
--    既存 chats テーブルは「会話セッション」レベル。
--    個別メッセージへの AI 関連メタは別テーブルで持つ（既存に影響を与えない）。
--    messages_log との関連は今後の実装フェーズで詰める。
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_chat_metadata (
  id                TEXT PRIMARY KEY,
  line_account_id   TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  friend_id         TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  chat_id           TEXT REFERENCES chats (id) ON DELETE SET NULL,
  message_text      TEXT,
  intent            TEXT,
  model_used        TEXT,
  input_tokens      INTEGER,
  output_tokens     INTEGER,
  cost_yen_x100     INTEGER,
  kb_chunks_used    TEXT,
  cached_response   INTEGER NOT NULL DEFAULT 0,
  escalated         INTEGER NOT NULL DEFAULT 0,
  vision_used       INTEGER NOT NULL DEFAULT 0,
  pii_masked        INTEGER NOT NULL DEFAULT 0,
  response_time_ms  INTEGER,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_metadata_account ON ai_chat_metadata (line_account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_chat_metadata_friend ON ai_chat_metadata (friend_id, created_at DESC);


-- ============================================================================
-- 5. AI 応答キャッシュ（コスト削減）
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_response_cache (
  id               TEXT PRIMARY KEY,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  question_hash    TEXT NOT NULL,
  question         TEXT NOT NULL,
  response         TEXT NOT NULL,
  model_used       TEXT,
  hit_count        INTEGER NOT NULL DEFAULT 0,
  last_used_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  expires_at       TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (line_account_id, question_hash)
);

CREATE INDEX IF NOT EXISTS idx_ai_cache_account_hash ON ai_response_cache (line_account_id, question_hash);
CREATE INDEX IF NOT EXISTS idx_ai_cache_expires ON ai_response_cache (expires_at);


-- ============================================================================
-- 6. 顧客 AI シグナル（intent score, churn risk, LTV, VIP rank）
--    既存 friend_scores や scoring_rules とは別軸で AI 推定値を保持。
--    既存スコア（行動ベース）と AI スコアを統合判断するロジックは UI 層。
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_friend_signals (
  friend_id           TEXT PRIMARY KEY REFERENCES friends (id) ON DELETE CASCADE,
  line_account_id     TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  purchase_intent     INTEGER NOT NULL DEFAULT 0,
  churn_risk          INTEGER NOT NULL DEFAULT 0,
  ltv_estimate_yen    INTEGER,
  vip_rank            TEXT CHECK (vip_rank IN ('vip', 'hot', 'warm', 'cold', 'dormant', 'new')),
  sentiment           TEXT CHECK (sentiment IN ('positive', 'neutral', 'negative', 'angry')),
  signal_summary      TEXT,
  last_chat_at        TEXT,
  last_calculated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ai_signals_account_rank ON ai_friend_signals (line_account_id, vip_rank);
CREATE INDEX IF NOT EXISTS idx_ai_signals_account_intent ON ai_friend_signals (line_account_id, purchase_intent DESC);
CREATE INDEX IF NOT EXISTS idx_ai_signals_churn ON ai_friend_signals (line_account_id, churn_risk DESC);


-- ============================================================================
-- 7. AI 使用ログ（コスト追跡、テナント計量の根拠データ）
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_usage_log (
  id               TEXT PRIMARY KEY,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  friend_id        TEXT REFERENCES friends (id) ON DELETE SET NULL,
  feature          TEXT NOT NULL CHECK (feature IN (
                     'chat', 'report', 'copy_gen', 'vision', 'intent',
                     'image_gen', 'batch_analysis', 'embedding', 'moderation'
                   )),
  model            TEXT NOT NULL,
  input_tokens     INTEGER NOT NULL DEFAULT 0,
  output_tokens    INTEGER NOT NULL DEFAULT 0,
  cost_yen_x100    INTEGER NOT NULL DEFAULT 0,
  cached           INTEGER NOT NULL DEFAULT 0,
  request_id       TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_account_date ON ai_usage_log (line_account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_feature ON ai_usage_log (line_account_id, feature, created_at DESC);


-- ============================================================================
-- 8. テナント計量（含有枠 + 当月使用 + 超過課金）
-- ============================================================================

CREATE TABLE IF NOT EXISTS tenant_metering (
  line_account_id            TEXT PRIMARY KEY REFERENCES line_accounts (id) ON DELETE CASCADE,
  plan                       TEXT NOT NULL DEFAULT 'lite'
                              CHECK (plan IN ('lite', 'standard', 'pro', 'enterprise')),

  monthly_broadcast_quota    INTEGER NOT NULL DEFAULT 0,
  monthly_chat_quota         INTEGER NOT NULL DEFAULT 0,
  monthly_vision_quota       INTEGER NOT NULL DEFAULT 0,
  monthly_imagegen_quota     INTEGER NOT NULL DEFAULT 0,
  monthly_kb_doc_quota       INTEGER NOT NULL DEFAULT 0,

  current_month              TEXT NOT NULL DEFAULT '',
  used_broadcast             INTEGER NOT NULL DEFAULT 0,
  used_chat                  INTEGER NOT NULL DEFAULT 0,
  used_vision                INTEGER NOT NULL DEFAULT 0,
  used_imagegen              INTEGER NOT NULL DEFAULT 0,
  used_kb_doc                INTEGER NOT NULL DEFAULT 0,

  overage_charge_yen         INTEGER NOT NULL DEFAULT 0,

  monthly_budget_cap_yen     INTEGER,
  alert_threshold_yen        INTEGER,
  auto_fallback_at_limit     INTEGER NOT NULL DEFAULT 1,

  -- 計量サイクル: 開始日時を設定すると「そこから 1 ヶ月ごと」にリセット。
  -- NULL = 未設定 → 暦月 (current_month) 基準のリセットにフォールバック。
  cycle_started_at           TEXT,
  cycle_resets_at            TEXT,

  updated_at                 TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);


-- ============================================================================
-- 9. 監査ログ（セキュリティ最重要：誰がいつ何をしたか）
-- ============================================================================

CREATE TABLE IF NOT EXISTS audit_log (
  id               TEXT PRIMARY KEY,
  line_account_id  TEXT REFERENCES line_accounts (id) ON DELETE SET NULL,
  staff_id         TEXT REFERENCES staff_members (id) ON DELETE SET NULL,
  action           TEXT NOT NULL,
  resource_type    TEXT,
  resource_id      TEXT,
  ip_address       TEXT,
  user_agent       TEXT,
  request_id       TEXT,
  details_json     TEXT,
  result           TEXT NOT NULL DEFAULT 'success'
                    CHECK (result IN ('success', 'failed', 'denied')),
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_audit_log_account_date ON audit_log (line_account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_staff ON audit_log (staff_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource ON audit_log (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log (action, created_at DESC);


-- ============================================================================
-- 10. PII 削除リクエスト（個人情報保護法対応）
-- ============================================================================

CREATE TABLE IF NOT EXISTS pii_deletion_requests (
  id                  TEXT PRIMARY KEY,
  line_account_id     TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  friend_id           TEXT REFERENCES friends (id) ON DELETE SET NULL,
  requested_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  requested_by        TEXT NOT NULL,
  reason              TEXT,
  status              TEXT NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending', 'processing', 'completed', 'denied', 'cancelled')),
  processed_at        TEXT,
  processed_by        TEXT REFERENCES staff_members (id) ON DELETE SET NULL,
  deletion_log_json   TEXT
);

CREATE INDEX IF NOT EXISTS idx_pii_deletion_account_status ON pii_deletion_requests (line_account_id, status);
CREATE INDEX IF NOT EXISTS idx_pii_deletion_friend ON pii_deletion_requests (friend_id);


-- ============================================================================
-- 11. 同意管理（AI 利用同意、データ処理同意）
-- ============================================================================

CREATE TABLE IF NOT EXISTS consent_records (
  id               TEXT PRIMARY KEY,
  line_account_id  TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  friend_id        TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  consent_type     TEXT NOT NULL CHECK (consent_type IN (
                     'ai_chat_processing', 'data_storage', 'marketing_delivery', 'profile_analysis'
                   )),
  granted          INTEGER NOT NULL DEFAULT 0,
  policy_version   TEXT,
  granted_at       TEXT,
  revoked_at       TEXT,
  ip_address       TEXT,
  user_agent       TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (friend_id, consent_type)
);

CREATE INDEX IF NOT EXISTS idx_consent_account_friend ON consent_records (line_account_id, friend_id);
CREATE INDEX IF NOT EXISTS idx_consent_type_granted ON consent_records (consent_type, granted);
-- ============================================================================
-- 042_l_assist_agent_engine.sql
--
-- L-アシスト KPI 駆動 AI 自動化エンジン
--
-- 目的:
--   事業者が KPI を設定 → AI がタスク分解 → ジョブキュー投入 → cron で順次実行
--   → レビューキュー振り分け、までの完全自律エンジン。
--
-- 設計方針:
--   - 既存テーブルへの ALTER は行わない（041 と同方針）
--   - 全テーブル line_account_id でテナント分離
--   - id は TEXT (UUID), 日時は TEXT ISO 8601 JST
--
-- 含むもの:
--   1. kpi_goals       事業者の月次 KPI 目標
--   2. agent_jobs      AI 実行ジョブのキュー
--   3. tenant_automation_policy  テナント別自動化レベル設定
-- ============================================================================


-- ============================================================================
-- 1. KPI 目標
-- ============================================================================

CREATE TABLE IF NOT EXISTS kpi_goals (
  id                TEXT PRIMARY KEY,
  line_account_id   TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  year_month        TEXT NOT NULL,
  metric            TEXT NOT NULL CHECK (metric IN (
                       'broadcast_count',       -- 月配信本数
                       'friend_growth',         -- 友だち純増
                       'cv_count',              -- コンバージョン件数
                       'reactivation_count',    -- 休眠掘り起こし件数
                       'open_rate',             -- 平均開封率
                       'click_rate',            -- 平均 CTR
                       'nps',                   -- NPS スコア
                       'reservation_count',     -- 予約件数
                       'review_count'           -- レビュー獲得件数
                     )),
  target_value      INTEGER NOT NULL,
  current_value     INTEGER NOT NULL DEFAULT 0,
  notes             TEXT,
  created_by        TEXT REFERENCES staff_members (id) ON DELETE SET NULL,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (line_account_id, year_month, metric)
);

CREATE INDEX IF NOT EXISTS idx_kpi_goals_account_month ON kpi_goals (line_account_id, year_month);


-- ============================================================================
-- 2. AI ジョブキュー
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_jobs (
  id                TEXT PRIMARY KEY,
  line_account_id   TEXT NOT NULL REFERENCES line_accounts (id) ON DELETE CASCADE,
  job_type          TEXT NOT NULL,
  input_json        TEXT NOT NULL DEFAULT '{}',
  origin            TEXT NOT NULL CHECK (origin IN (
                       'kpi_planner', 'manual', 'automation', 'cron', 'webhook'
                     )),
  related_kpi_id    TEXT REFERENCES kpi_goals (id) ON DELETE SET NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
                     CHECK (status IN (
                       'pending', 'running', 'review', 'approved',
                       'rejected', 'completed', 'failed', 'cancelled'
                     )),
  scheduled_at      TEXT NOT NULL,
  started_at        TEXT,
  completed_at      TEXT,
  output_json       TEXT,
  cost_yen_x100     INTEGER NOT NULL DEFAULT 0,
  retries           INTEGER NOT NULL DEFAULT 0,
  max_retries       INTEGER NOT NULL DEFAULT 3,
  error             TEXT,
  reviewer_id       TEXT REFERENCES staff_members (id) ON DELETE SET NULL,
  reviewed_at       TEXT,
  notes             TEXT,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_agent_jobs_account_status ON agent_jobs (line_account_id, status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_pending_due  ON agent_jobs (status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_kpi          ON agent_jobs (related_kpi_id);
CREATE INDEX IF NOT EXISTS idx_agent_jobs_review       ON agent_jobs (line_account_id, status) WHERE status = 'review';


-- ============================================================================
-- 3. テナント別自動化ポリシー
--    どのジョブ種別を自動公開し、どれを人間レビューに回すかを設定
-- ============================================================================

CREATE TABLE IF NOT EXISTS tenant_automation_policy (
  line_account_id   TEXT PRIMARY KEY REFERENCES line_accounts (id) ON DELETE CASCADE,
  automation_level  TEXT NOT NULL DEFAULT 'careful'
                     CHECK (automation_level IN ('careful', 'standard', 'aggressive')),
  job_overrides_json TEXT,  -- {"generate_broadcast": "auto", "wake_dormant": "review"} 等
  notification_channel TEXT DEFAULT 'line',  -- 承認待ち通知の宛先
  notification_target TEXT,                  -- LINE 通知先 user_id 等
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);
